name: gift_box
description: A new Flutter project.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

  # Navigator
  go_router: ^16.0.0

  # State Management
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0

  # UI
  animated_flip_counter: ^0.3.4
  animated_text_kit: ^4.2.3
  confetti: ^0.8.0
  rive: ^0.14.0-dev.6

  # Utils
  clock: ^1.1.2
  collection: ^1.19.0
  equatable: ^2.0.5
  get_it: ^9.0.5
  hive_ce: ^2.11.3
  just_audio: ^0.10.4
  logger: ^2.4.0
  nfc_manager:
    git:
      url: https://github.com/ngoc-quoc-huynh/nfc_manager.git
      path: nfc_manager
      ref: v1.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  # Linter
  cosee_lints: ^0.11.0
  dart_code_linter: ^3.0.0

  # Localization
  slang_flutter: ^4.0.0
  slang_build_runner: ^4.0.0

  # Launcher icon
  flutter_launcher_icons: ^0.14.1

  # Splash Screen
  flutter_native_splash: ^2.4.1

  # Test
  flutter_test:
    sdk: flutter
  alchemist: ^0.12.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/audios/ada/
    - assets/audios/music_tape/
    - assets/images/carousel/
    - assets/images/shop/
    - assets/rive/
