name: gift_box
description: A new Flutter project.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Utils
  get_it: ^9.0.5
  logger: ^2.6.2
  nfc_manager:
    git:
      url: https://github.com/ngoc-quoc-huynh/nfc_manager.git
      path: nfc_manager
      ref: v1.1.0

dev_dependencies:
  # Linter
  cosee_lints: ^0.11.0
  dart_code_linter: ^3.1.1
